### ISSUE TITLE
Filtering for SN type doesn't work

### ISSUE THREAD

**Issue by dobos** [astrocatalogs/OACAPI#1]
Hi,

I'm trying to retreive type Ia supernovae but neither filtering for attributes nor cvs formatting don't seem to work. For instance, when I try the url

    https://api.sne.space/all/redshift/value?claimedtype=Ia&format=csv

I get the whole catalog in JSON.

**Comment by guillochon** [comment]
Thanks @dobos, I verify that this isn't working correctly. I will look into it later today.

**Comment by dobos** [comment]
Thanks, absolutely no hurries.

**Comment by guillochon** [comment]
Hi @dobos, this should be working now; one caveat though is that you shouldn't include `value` in your query, the query should look like this:

    https://api.sne.space/all/redshift?claimedtype=Ia&format=csv

The query filters only apply to the last layer in the route, so for instance you can't filter on `claimedtype` because `value` is the last layer (and `claimedtype` lives in the `QUANTITY` layer only).

Let me know if this does what you were looking to do.
